### ISSUE TITLE
proxy function not working

### ISSUE THREAD

**Issue by superuser5** [milo2012/pathbrute#4]
Hi
I am running pathbrute through the proxy and requests execute directly on Linux and MacOS bypassing http or socks5 proxy:
./pathBrute --update -u google.com -p test -v --pHost 127.0.0.1

[*] Testing URI Paths: (Total: 2)
http://google.com/test [404] [1565] [Error 404 (Not Found)!!1] [2 of 2]

[*] No results found

or even wrong IP, which should timeout or cause error
./pathBrute --update -u google.com -p test -v --pHost **123.123.123.123**

[*] Testing URI Paths: (Total: 2)
http://google.com/test [404] [1565] [Error 404 (Not Found)!!1] [2 of 2]

[*] No results found

**Comment by milo2012** [comment]
Sorry for the late response.  I missed this issue
It should be ok now for http proxy.  I have tested it with Burp proxy.

**Comment by superuser5** [comment]
apologies for the delay retesting the issue. I tested and it works now.
