### ISSUE TITLE
Feature: Remove pathBrute_osx and pathBrute_linux from master

### ISSUE THREAD

**Issue by Chan9390** [milo2012/pathbrute#5]
Hey,

I can see that the compiled files `pathBrute_osx` and `pathBrute_linux` are included in the master branch. Also the executables are compiled for different OS & architectures and are made available at releases page. I would suggest you to remove them from the branch as it would take away more space (considering the project in long term).

If you have included them just for the sake of Dockerfile, you can change the command `ADD pathBrute_linux /` to a bunch of commands which includes installing wget, download the executable from release and then executing it.

**Comment by Ice3man543** [comment]
I agree with Badshah. Also, you should consider doing a full delete since git preserves The file in history. 

I loved the awesome wordlists you have got there. Great work.

**Comment by milo2012** [comment]
Thanks @Ice3man543 and @Chan9390 
I have removed the files.  I am still checking on how to do a full delete as I am still a newbie to git.  

Partially resolved in commit 333307a

**Comment by Ice3man543** [comment]
@milo2012 here you go - https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by milo2012** [comment]
Thank you once again @Ice3man543

**Comment by Ice3man543** [comment]
Once fixed, ping me so that I can clone it. It's too big. 103 mb repo is huge for me.

**Comment by Chan9390** [comment]
@Ice3man543 One trick which would work is clone with depth 1. `git clone <address> --depth=1`
Doing so you will only download the latest commit and you can build upon that. But there are disadvantages too.

**Comment by milo2012** [comment]
Its been reduced to 27MB.

$ git clone https://github.com/milo2012/pathbrute
Cloning into 'pathbrute'...
remote: Counting objects: 860, done.
remote: Compressing objects: 100% (275/275), done.
remote: Total 860 (delta 242), reused 512 (delta 241), pack-reused 344
Receiving objects: 100% (860/860), **27.02 MiB** | 7.94 MiB/s, done.
Resolving deltas: 100% (540/540), done.

**Comment by Chan9390** [comment]
@milo2012 Which file takes the most space now ?

**Comment by Chan9390** [comment]
Closing the issue as the executables were removed from master branch
