### ISSUE TITLE
additonal requirements

### ISSUE THREAD

**Issue by ITmustang** [milo2012/pathbrute#9]
more of a notice...
manual compilation reads..
go github.com/hashicorp/go-version
however, it should be 
go get github.com/hashicorp/go-version   correct?

also, maybe consider putting the following in readme for manual compilation as they came up as a requirement to successfully build for me...
 
go get github.com/xrash/smetrics
go get github.com/ti/nasync

**Comment by milo2012** [comment]
Updated the readme.  Thank you for your contribution.
